## $$PYTHON\:\:第四课$$

### 课程安排:
    1.numpy
    2.pandas
    3.matplotlib

#### Numpy

    数组和列表有一定的联和区别，列表可以存储任意类型的数据，而数组只能存储一种类型的数据

In [6]:
import array
a = array.array('i',range(10))

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np
a_list = list(range(1,10))
b = np.array(a_list)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 生成数组

In [4]:
a = np.zeros(10,dtype=int)
# 查看数组类型 
a.dtype   # a_list
a1 = np.zeros((4,4),dtype=int)
a2 = np.ones((4,4),dtype=float)
a3 = np.full((3,3),3.14)

np.full_like(a1,2.222,dtype=float)

array([[2.222, 2.222, 2.222, 2.222],
       [2.222, 2.222, 2.222, 2.222],
       [2.222, 2.222, 2.222, 2.222],
       [2.222, 2.222, 2.222, 2.222]])

### random

In [242]:
import random
# 5-10 的整数
a = random.randint(5,10)
# 0-1 的小数
b = random.random()
b

0.09808761188089998

In [249]:
# 不同维度的小数
c = np.random.random((3,3))
# shape=(2,2) 每个元素为：0-9的整数
# 常用
d = np.random.randint(0,10,(2,2))
d

array([[7, 2],
       [7, 9]])

##### 范围取值

In [250]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [251]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [260]:
# 常用
# 0-10 取5个等步长的数
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [259]:
# n维的单位矩阵
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

##### 访问数组中的元素

In [262]:
# 嵌套列表的元素访问
var = [[1,2,3],[3,4,5],[6,7,8]]
var[0][0]

1

In [272]:
a = np.array(var)
# 数组中元素的访问
a

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [276]:
# 两种访问方式是等价的
a[0][0],a[0,0]

(1, 1)

In [277]:
a[:2,:2]

array([[1, 2],
       [3, 4]])

In [283]:
# 切片访问时，两种方式不一样
a[:2][:2]

array([[1, 2, 3],
       [3, 4, 5]])

In [284]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [292]:
# 维度
a.ndim # 2
# shape
a.shape # (3, 3)
# size 
a.size # 9
# dtype
a.dtype # int32
# itemsize 一个字节占8位,4个就是32位
a.itemsize # 4
# nbytes 4*9
a.nbytes # 36

36

### 统计类型

In [303]:
# 求和
sum([1,2,3,4,5,6])
a = np.full(10,2.3)
sum(a)
b = np.full((4,3),2.3)
np.sum(b,axis=1),b
np.max(b)

2.3

In [304]:
n = np.random.random(1000)

### notbook使用小技巧

%timeit代码；此方法用来判断程序的执行效率

In [306]:
%timeit sum(n)

10000 loops, best of 3: 88 µs per loop


In [307]:
%timeit np.sum(n)

The slowest run took 15.32 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.36 µs per loop


##### 由上代码可看出np.sum的执行效率高，推荐使用

#### 比较

In [308]:
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [309]:
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [312]:
np.all(a>1)

False

In [313]:
np.any(a>-1)

True

#### 变形

In [372]:
a = np.full((2,10),1,dtype=float)

In [373]:
a.reshape(4,5)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### 排序

In [374]:
a = [
    [1,2,3],
    [32,12,4],
    [32,2,33]
]
a = np.array(a)
np.sort(a)

array([[ 1,  2,  3],
       [ 4, 12, 32],
       [ 2, 32, 33]])

In [375]:
# 改变原数组的顺序
a.sort()

In [376]:
a

array([[ 1,  2,  3],
       [ 4, 12, 32],
       [ 2, 32, 33]])

#### 拼接

In [377]:
a = np.array([1,2,3])
b = np.array([[0,2,4],[1,3,5],[7,8,9]])

In [378]:
np.concatenate([b,b],axis=0)


array([[0, 2, 4],
       [1, 3, 5],
       [7, 8, 9],
       [0, 2, 4],
       [1, 3, 5],
       [7, 8, 9]])

In [382]:
# 新的格式.csv
import pandas as pd

In [393]:
df = pd.read_csv(u'..\\111.csv',encoding='utf8')
df.head() # 默认读取前五行

日期    燃气用量   湿度极差归一化  pm2.5归一化    AQI归一化   季节因素归一化
0  1/1/16 12:00 AM  405.81  0.715976  0.772973  0.799087  0.266362
1  1/2/16 12:00 AM  357.42  0.479290  0.740541  0.757991  0.252664
2  1/3/16 12:00 AM  350.44  0.805391  0.562162  0.561644  0.187215
3  1/4/16 12:00 AM  397.47  0.213018  0.621622  0.625571  0.208524
4  1/5/16 12:00 AM  382.64  0.515450  0.745946  0.767123  0.255708

In [394]:
type(df)

pandas.core.frame.DataFrame

##### DataFrame

In [397]:
# 别名
print(df.columns)
# 索引
print(df.index)

Index(['日期', '燃气用量', '湿度极差归一化', 'pm2.5归一化', 'AQI归一化', '季节因素归一化'], dtype='object')
RangeIndex(start=0, stop=366, step=1)


In [399]:
df.loc[4]

日期          1/5/16 12:00 AM
燃气用量                 382.64
湿度极差归一化             0.51545
pm2.5归一化           0.745946
AQI归一化             0.767123
季节因素归一化            0.255708
Name: 4, dtype: object

In [400]:
df.AQI归一化 > 0.5

0       True
1       True
2       True
3       True
4       True
5       True
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18      True
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28      True
29      True
       ...  
336     True
337     True
338     True
339     True
340     True
341     True
342     True
343     True
344     True
345    False
346    False
347    False
348    False
349     True
350     True
351    False
352     True
353     True
354     True
355     True
356     True
357     True
358    False
359    False
360    False
361    False
362    False
363    False
364    False
365     True
Name: AQI归一化, Length: 366, dtype: bool

In [404]:
df[(df.AQI归一化>0.7) & (df.季节因素归一化 > 0.3)]

日期    燃气用量  湿度极差归一化  pm2.5归一化  AQI归一化   季节因素归一化
354  12/20/16 12:00 AM  464.63      1.0       1.0     1.0  0.333333

### 排序

In [406]:
df.sort_values(['燃气用量']).head()

日期    燃气用量   湿度极差归一化  pm2.5归一化    AQI归一化   季节因素归一化
278  10/5/16 12:00 AM  180.69  0.378698  0.108108  0.105023  0.035008
233  8/21/16 12:00 AM  185.82  0.552926  0.232432  0.315068  0.105023
277  10/4/16 12:00 AM  187.68  0.262985  0.372973  0.397260  0.132420
241  8/29/16 12:00 AM  188.45  2.211703  0.108108  0.095890  0.031963
239  8/27/16 12:00 AM  189.40  0.479290  0.054054  0.132420  0.044140

### 访问

In [409]:
# 按照索引去定位
df.loc[4]

日期          1/5/16 12:00 AM
燃气用量                 382.64
湿度极差归一化             0.51545
pm2.5归一化           0.745946
AQI归一化             0.767123
季节因素归一化            0.255708
Name: 4, dtype: object

In [411]:

df.iloc[4]

日期          1/5/16 12:00 AM
燃气用量                 382.64
湿度极差归一化             0.51545
pm2.5归一化           0.745946
AQI归一化             0.767123
季节因素归一化            0.255708
Name: 4, dtype: object

In [412]:
# 
df.ix[0]

D:\Environment_java_python\python\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


日期          1/1/16 12:00 AM
燃气用量                 405.81
湿度极差归一化            0.715976
pm2.5归一化           0.772973
AQI归一化             0.799087
季节因素归一化            0.266362
Name: 0, dtype: object